### ISSUE TITLE
For your information

### ISSUE THREAD

**Issue by polluks** [SvenMichaelKlose/vic-8080#1]
https://www.pagetable.com/?p=1315 :-)

**Comment by SvenMichaelKlose** [comment]
Cool! Thanks! My version would be a lot faster, I assume. But I guess I was too high or something sketching this, because CP/M does not seem to make much sense on a low-res VIC display.

**Comment by polluks** [comment]
Indeed, you may use soft 40 columns, but the TPA would getting even smaller.
Or something like this http://sleepingelephant.com/denial/wiki/index.php?title=40_and_80_column_boards

**Comment by SvenMichaelKlose** [comment]
Oh, forgot to mention that this is designed to run on the Ultimem expansion. Any CP/M software out there that'd be nice to have on a 40 column terminal?

**Comment by polluks** [comment]
Please take a look https://retrocomputing.stackexchange.com/questions/6932/cp-m-in-less-than-80-columns/7041#7041

**Comment by SvenMichaelKlose** [comment]
Oh-oh. WordStar and Turbo Pascal on a VIC. That's usually when people wake up and get disappointed. ;) Thank you! Now I'll be thinking about it all day. :p
